### ISSUE TITLE
Xamarin Forms

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [NAXAM/jwplayer-android-binding#1]
is it possible to use with xamarin forms (Android)?

**Comment by tuyen-vuduc** [comment]
Yes, you will need to custom control or we have a paid package if you want to have both on Android and iOS.

**Comment by andersonvieiragomeslopes** [comment]
Do you have any documents about this? My project is didactic for now.

**Comment by tuyen-vuduc** [comment]
There is no special instruction required, plz follow Xamarin.Forms custom renderer and JWPlayer document to create the control yourself. 

If you want the paid package, plz drop me an email I will send the detail.

**Comment by andersonvieiragomeslopes** [comment]
How much are we talking about? 10 dollars? 20 dollars? Would you create everything or just send information?

**Comment by andersonvieiragomeslopes** [comment]
@tuyen-vuduc I sent you an e-mail
